### ISSUE TITLE
date param to TimeStamp produces timestamps for next day

### ISSUE THREAD

**Issue by greenape** [maxalbert/tohu#3]
When using the `TimeStamp` generator, if I provide a `date` parameter, I will sometimes get timestamps for midnight the next day. Seems to be because adding a 1 day delta from midnight one day puts you at midnight the next. I can achieve the desired outcome (timestamps within a single day) but setting `start` and `end` to the same value, because `end` goes to 23:59:59 of the day.

**Comment by maxalbert** [comment]
Good catch, thanks!
